ARG BASE=ubuntu:24.04
FROM $BASE

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
        clang-format-16 \
        git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CLANG_FORMAT_EXE=clang-format-16
